### ISSUE TITLE
[Bug]: Can't access UI

### ISSUE THREAD

**Issue by krzwiatrzyk** [govirtuo/kube-ns-suspender#78]
### Current Behavior:

I have tried to access UI using port forward for 8080 in the pod and it is not working. Is any additional configuration required?

**Comment by eze-kiel** [comment]
hi @krzwiatrzyk,
did you use the flag `--ui-embedded`?

https://github.com/govirtuo/kube-ns-suspender#flags

**Comment by krzwiatrzyk** [comment]
I have set an environment variable in following way:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ns-suspender
  namespace: kube-ns-suspender
  labels:
    app: kube-ns-suspender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ns-suspender
  template:
    metadata:
      labels:
        app: kube-ns-suspender
    spec:
      serviceAccountName: kube-ns-suspender
      containers:
      - name: kube-ns-suspender
        image: ghcr.io/govirtuo/kube-ns-suspender:v0.7.4
        ports:
        - name: metrics
          containerPort: 2112
        - name: webui
          containerPort: 8080
        env:
        - name: "KUBE_NS_SUSPENDER_UI_EMBEDDED"
          value: "true"
 ```
